# Optimization & Training (Beginner)

- tf와 layers 패키지 불러오기

In [1]:
import tensorflow as tf
from tensorflow.keras import layers

from tensorflow.keras import datasets
import numpy as np

## 학습 과정 돌아보기

# Prepare MNIST Datset

In [2]:
(train_x, train_y), (test_x, test_y) = datasets.mnist.load_data()

In [3]:
np.min(train_x), np.max(train_x)

(0, 255)

## Build Model

In [4]:
inputs = layers.Input((28, 28, 1))
net = layers.Conv2D(32, (3, 3), padding='SAME')(inputs)
net = layers.Activation('relu')(net)
net = layers.Conv2D(32, (3, 3), padding='SAME')(net)
net = layers.Activation('relu')(net)
net = layers.MaxPooling2D(pool_size=(2, 2))(net)
net = layers.Dropout(0.25)(net)

net = layers.Conv2D(64, (3, 3), padding='SAME')(net)
net = layers.Activation('relu')(net)
net = layers.Conv2D(64, (3, 3), padding='SAME')(net)
net = layers.Activation('relu')(net)
net = layers.MaxPooling2D(pool_size=(2, 2))(net)
net = layers.Dropout(0.25)(net)

net = layers.Flatten()(net)
net = layers.Dense(512)(net)
net = layers.Activation('relu')(net)
net = layers.Dropout(0.5)(net)
net = layers.Dense(10)(net)  # num_classes
net = layers.Activation('softmax')(net)

model = tf.keras.Model(inputs=inputs, outputs=net, name='Basic_CNN')

# Optimization  
모델을 학습하기 전 설정 

- Loss Function  
- Optimization  
- Metrics

# Loss Function  
Loss Function 방법 확인

### Categorical vs Binary

In [5]:
loss = 'binary_crossentropy'
loss = 'categorcal_crossentropy'

### sparse_categorical_crossentropy vs categorical_crossentropy

- sparse_categorical_crossentropy
```
y_true = [1, 2]
y_pred = [[0.05,0.95,0], [0.1,0.8,0.1]]
loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
print(loss)
tf.Tensor([0.05129, 2.30258], shape=(2,), dtype=float32)
```

- categorical_crossentropy
```
y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.05,0.95,0], [0.1,0.8,0.1]]
loss = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
print(loss)
tf.Tensor([0.05129, 2.30258], shape=(2,), dtype=float32)
```

In [6]:
loss_fun = tf.keras.losses.sparse_categorical_crossentropy

In [7]:
tf.keras.losses.categorical_crossentropy

<function tensorflow.python.keras.losses.categorical_crossentropy(y_true, y_pred, from_logits=False, label_smoothing=0)>

In [8]:
# 바이너리로 주는 경우
tf.keras.losses.binary_crossentropy

<function tensorflow.python.keras.losses.binary_crossentropy(y_true, y_pred, from_logits=False, label_smoothing=0)>

# Metrics  

모델을 평가하는 방법

accuracy를 이름으로 넣는 방법

In [9]:
metrics = ['accuracy']

tf.keras.metrics.

In [10]:
tf.keras.metrics.Accuracy()
tf.keras.metrics.Precision()
tf.keras.metrics.Recall()

In [11]:
metrics = [tf.keras.metrics.Accuracy()]

## Compile  
Optimizer 적용

- 'sgd'
- 'rmsprop'
- 'adam'

In [12]:
optm = tf.keras.optimizers.Adam()

- tf.keras.optimizers.SGD()  
- tf.keras.optimizers.RMSprop()    
- tf.keras.optimizers.Adam()  

In [13]:
model.compile(optimizer=optm,
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'], 
              )

In [14]:
model.compile(optimizer=optm,
              loss='sparse_categorical_crossentropy',
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy()] 
              #not this!! --> [tf.keras.metrics.Accuracy()]
              )

# Prepare Dataset  
학습에 사용할 데이터셋 준비

shape 확인

In [15]:
train_x.shape, train_y.shape

((60000, 28, 28), (60000,))

In [16]:
test_x.shape, test_y.shape

((10000, 28, 28), (10000,))

차원 수 늘리기

In [17]:
import numpy as np

In [18]:
np.expand_dims(train_x, -1).shape

(60000, 28, 28, 1)

In [19]:
tf.expand_dims(train_x, -1).shape

TensorShape([60000, 28, 28, 1])

In [20]:
train_x = train_x[..., tf.newaxis]
test_x = test_x[..., tf.newaxis]

차원 수 잘 늘었는지 확인

In [21]:
train_x.shape

(60000, 28, 28, 1)

In [22]:
test_x.shape

(10000, 28, 28, 1)

Rescaling

In [23]:
np.min(train_x), np.max(train_x)

(0, 255)

In [24]:
train_x = train_x / 255.
test_x = test_x / 255.

In [25]:
np.min(train_x), np.max(train_x)

(0.0, 1.0)

In [26]:
train_y

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

# Training  
본격적으로 학습 들어가기

학습용 Hyperparameter 설정

- num_epochs
- batch_size

In [27]:
num_epochs = 1
batch_size = 32

- model.fit

In [28]:
hist = model.fit(train_x, train_y,
                 batch_size=batch_size,
                 shuffle=True,
                 epochs=num_epochs)

1875/1875 [==============================] - 203s 108ms/step - loss: 0.1537 - sparse_categorical_accuracy: 0.9507s - loss: 0.1541 - sparse_categorical_accuracy:


In [ ]:
hist.history

# Check History  
학습 과정(History) 결과 확인

In [29]:
model.summary()

Model: "Basic_CNN"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 28, 28, 1)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 28, 28, 32)        320       
_________________________________________________________________
activation (Activation)      (None, 28, 28, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 32)        9248      
_________________________________________________________________
activation_1 (Activation)    (None, 28, 28, 32)        0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 32)        0         
_________________________________________________________________
dropout (Dropout)            (None, 14, 14, 32)        0 